# Generated by Django 4.2.5 on 2023-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_name', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('is_sale', models.BooleanField(default=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
